name: native_widgets
description: A new Flutter package for using Android and iOS natively on each platform.
version: 1.3.7+1
publish_to: none
author: Rhodes Davis Jr. <rody.davis.jr@gmail.com>
homepage: https://github.com/fluttercommunity/native_widgets
maintainer: Rody Davis (@rodydavis)

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_sticky_header: ^0.4.0
  uuid: ^3.0.1
  intl: ^0.17.0
  flutter_list_drag_and_drop:
    git :
      url: https://github.com/kiratheone/flutter_list_drag_and_drop
  flutter_slidable: ^0.6.0
  flutter_platform_widgets: ^1.9.5

dev_dependencies:
  flutter_test:
    sdk: flutter

# dependency_overrides:
#   flutter_sticky_header:
#     git: https://github.com/rodydavis/flutter_sticky_header

flutter:
